### ISSUE TITLE
Height Calculation Issue using CollectionBrick for a carousel

### ISSUE THREAD

**Issue by wfsttam** [wayfair/brickkit-ios#118]
A chunk of blank space appears when above the space I use a collection brick to create a carousel. Invalidating the brick collection view will fix the problem and the missing bricks will appear and the height will get calculated properly.

**Comment by rubencagnie** [comment]
@wfsttam, this PR will probably fix your issue. Can you verify?
https://github.com/wayfair/brickkit-ios/pull/144

**Comment by wfsttam** [comment]
Looks good to me. I don’t have a place where I can easily check and reproduce but I will keep an eye out for the bug and let you know if I see it again. Thanks!
