### ISSUE TITLE
Did you want to review the spelling of behavior ?

### ISSUE THREAD

**Issue by jeis2497052** [wayfair/brickkit-ios#205]
Hi All,

should behavior be corrected ?

->  `BrickAppearBehavior ` is extendable, so you can create your own behavor
+>  `BrickAppearBehavior ` is extendable, so you can create your own behavior

![wayfair brickkit behavor 7 dec 2017](https://user-images.githubusercontent.com/32205350/33730802-17d6e716-db4f-11e7-9b77-a17c283fe252.png)

 

-> `BrickLayoutBehavior` is extendable, so are free to create your own behavors.
+> `BrickLayoutBehavior` is extendable, so are free to create your own behaviors.

**Comment by draco2003** [comment]
Thanks!
