### ISSUE TITLE
Push 2.4.2 to trunk to enable use of Swift 4.0 compatible BrickKit in podspec

### ISSUE THREAD

**Issue by scottcarter** [wayfair/brickkit-ios#207]
It appears that only minor versions are being pushed to CocoaPods/Specs 
https://github.com/CocoaPods/Specs/search?q=BrickKit&type=Commits

Could you consider pushing 2.4.2 to the trunk as an exception?

I'd like to use BrickKit as a dependency in a podspec I am creating, but am currently limited to using 2.4.0 which is not Swift 4.0 compatible.    Since podspecs don't currently support a mix of Swift 3.2/4.0     (https://github.com/CocoaPods/CocoaPods/issues/7134) the podspec can only use Swift 3.2 pod dependencies if BrickKit is included.

While a Podfile can specify a pod that is not yet pushed to the trunk (using :git and :tag), a podspec cannot do the same with a dependency.

Thanks for considering this request.

**Comment by jay18001** [comment]
I had to upgrade to 2.4.3 because I forgot to switch the swift version number
