### ISSUE TITLE
 compiled with older version of Swift language 

### ISSUE THREAD

**Issue by abdualrhmanio** [wayfair/brickkit-ios#21]
> BrickKit.framework/BrickKit compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

how can i slove this 

thank you

**Comment by rubencagnie** [comment]
@abdualrhmanIO this is on the roadmap to finish before the end of the year. We'll keep you posted

**Comment by rubencagnie** [comment]
@abdualrhmanIO We have a branch (https://github.com/wayfair/brickkit-ios/tree/swift3) up, if you'd like to test our swift 3 migration

**Comment by jay18001** [comment]
2.0.0 has been released
