### ISSUE TITLE
Brick Dimension Size Classes Issue

### ISSUE THREAD

**Issue by thevwu** [wayfair/brickkit-ios#6]
We use size classes to define standard width and heights to use across multiple devices and orientations. Following is the code that was used to define variable width ratio for iPad and iPhone.
`width: BrickDimension.HorizontalSizeClass(regular: .Orientation(landscape: .Ratio(ratio: 1/5), portrait: .Ratio(ratio: 1/4)), compact: .Ratio(ratio: 1/2))`

It seems to be working fine except while running on iPad mini device. When app starts, it shows 5 items in row for portrait iPad mode. (As opposed to 4 as defined in the layout). Switch the device to landscape mode and it shows 5 items as expected for that orientation. Now, if the device rotated back to the portrait mode, it correctly shows 4 items. Looks like the switching of orientations is required to show desired number of horizontal items for a mini.

**Comment by rubencagnie** [comment]
Closed by https://github.com/wayfair/brickkit-ios/pull/7
